server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: hrms-service
          uri: lb://hrms-service
          predicates:
            - Path=/hrms/**

        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/attendance/**

        - id: chatbot-service
          uri: lb://chatbot-service
          predicates:
            - Path=/chatbot/**
