server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/erp_auth
    username: postgres
    password: Aniket9867
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: ERP_SUPER_SECRET_KEY_123456
  expiration: 900000        # 15 minutes
  refresh-expiration: 604800000 # 7 days
