server:
  port: 8085

spring:
  application:
    name: chatbot-service

chatbot:
  mode: hybrid          # rule-based + AI
  ai:
    provider: gemini    # gemini / openai / llama
    api-key: YOUR_AI_API_KEY

security:
  jwt:
    public-key: 2gEkSGcACElSYAK72GzjxCX4/QTr1kKvDWZXbh2I5Zj2SYBUL3HX1rGYnnfP91L7cEwAHW61eX2C6e2XvMLAeQ==
