server:
  port: 8083

spring:
  application:
    name: hrms-service

  datasource:
    url: jdbc:postgresql://localhost:5432/erp_hrms
    username: postgres
    password: Aniket9867

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

hrms:
  leave:
    max-per-year: 24
