server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/erp_user
    username: postgres
    password: Aniket9867

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    public-key: ERP_SUPER_SECRET_KEY_123456
